name: tagpr
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions: write-all
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Check out source code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Run tagpr
        uses: Songmu/tagpr@7ebae2dcc300132baa7cc9dd108c8923b07fc366 # v1.20.3
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
